// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTm0ocKlCUJK6Mj9YwVD24bvmK_GUTJ9Y',
    appId: '1:376504874781:web:1a1f00fc00c4e1df9fd3f4',
    messagingSenderId: '376504874781',
    projectId: 'own-a-home-d5ad0',
    authDomain: 'own-a-home-d5ad0.firebaseapp.com',
    storageBucket: 'own-a-home-d5ad0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVcG5dZzsLUXL5EtOzLaFVEUTFxm-n_3A',
    appId: '1:376504874781:android:3de3989bf636f16b9fd3f4',
    messagingSenderId: '376504874781',
    projectId: 'own-a-home-d5ad0',
    storageBucket: 'own-a-home-d5ad0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHSvE1mCxpvCfSSyvs2ou75KlpZ498YjA',
    appId: '1:376504874781:ios:fcbdc4bdc37fc7269fd3f4',
    messagingSenderId: '376504874781',
    projectId: 'own-a-home-d5ad0',
    storageBucket: 'own-a-home-d5ad0.appspot.com',
    iosClientId: '376504874781-kfakg7p8gp5prk7vbr7t6ais5jie8u76.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHSvE1mCxpvCfSSyvs2ou75KlpZ498YjA',
    appId: '1:376504874781:ios:9e4d0ad4be9cbdec9fd3f4',
    messagingSenderId: '376504874781',
    projectId: 'own-a-home-d5ad0',
    storageBucket: 'own-a-home-d5ad0.appspot.com',
    iosClientId: '376504874781-iq40ehhked38bo9go426g5e87obalni9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
